services:
  recallrai-demo-email-agent:
    image: recallrai/recallrai-demo-email-agent:latest
    container_name: recallrai-demo-email-agent
    restart: unless-stopped
    build:
      context: email-agent
      dockerfile: Dockerfile
    command: streamlit run main.py --server.port 80
    volumes:
      - ./email-agent:/app
    labels:
      - traefik.enable=true
      - traefik.http.routers.recallrai-demo-email-agent.rule=Host(`email-agent-demo.recallrai.com`)
      - traefik.http.routers.recallrai-demo-email-agent.entrypoints=recallrai
      - traefik.http.services.recallrai-demo-email-agent.loadbalancer.server.port=80
    networks:
      - recallrai_prod

networks:
  recallrai_prod:
    external: true
