services:
  recallrai-wa-wati-customer-support-bot-demo:
    image: recallrai/recallrai-wa-wati-customer-support-bot-demo:latest
    container_name: recallrai-wa-wati-customer-support-bot-demo
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 main.py
    volumes:
      - .:/app
    labels:
      - traefik.enable=true
      - traefik.http.routers.recallrai-wa-wati-customer-support-bot-demo.rule=Host(`recallrai-wa-wati-customer-support-bot-demo.recallrai.com`)
      - traefik.http.routers.recallrai-wa-wati-customer-support-bot-demo.entrypoints=recallrai
      - traefik.http.services.recallrai-wa-wati-customer-support-bot-demo.loadbalancer.server.port=80
    network_mode: bridge
